### ISSUE TITLE
No updates for 2023.07

### ISSUE THREAD

**Issue by ReverendRhyme** [OSDeploy/OSDSUS#6]
No updates for 2023.07. Could we get this updated, please? Or how can we automate the catalog creation to build itself when launched?

**Comment by OSDeploy** [comment]
I'm aware.  I will update it when time permits, unfortunately I no longer work in OSD and WSUS during the week, so I do these updates in my free time, which is challenging during the week.  I will try to get it updated this weekend (no guarantees).

Also when you use the word "we", are you offering to contribute?  You're free to do a PR and make the updates.  As for me, I have no plans to add functionality to the WSUS updates, including automating the process, as I'm working on other projects.

So I guess since I'm leaving the "we" and leaving you, how are you going to automate the catalog creation to build itself when launched?   I'm curious ...

**Comment by xe0n11** [comment]
I'd like to assist providing catalog updates. If you're happy to share the process of creating the catalog files I'll do them ASAP on Patch Tuesdays.

Cheers!

**Comment by JeeBee14** [comment]
I would also like to help automate the catalog update process, depending on how it is done at the moment.

**Comment by steom** [comment]
> I would also like to help automating the catalog update process, depending on how it is done at the moment.

painstakingly manually 🥳

**Comment by OSDeploy** [comment]
Thanks everyone ... I've pushed the updates on Sunday evening, can someone validate they are working?

**Comment by apila22** [comment]
> Thanks everyone ... I've pushed the updates on Sunday evening, can someone validate they are working?

 Save-OSDBuilderDownload -Download -UpdateArch x64 -UpdateBuild 22H2 -UpdateOS 'Windows 11' -GridView

Does not show:
7/11/2023 5:00:06 PM   5028312  2023-07 Dynamic Update for Windows 11 for x64-based Systems (KB5028312)

Save-OSDBuilderDownload -Download -UpdateArch x64 -UpdateBuild 22H2 -UpdateOS 'Windows 10' -GridView

No longer has dynamic updates, updates.md is only listing the x86:
7/11/2023 5:00:06 PM   5028311  2023-07 Dynamic Update for Windows 10 for x86-based Systems (KB5028311)

Last month had x64:
6/13/2023 5:00:06 PM   5027389  2023-06 Dynamic Update for Windows 10 for x64-based Systems (KB5027389)

**Comment by xe0n11** [comment]
> Thanks everyone ... I've pushed the updates on Sunday evening, can someone validate they are working?

Can confirm 2023-07 updates downloaded and were applied to media successfully (Windows 11\Server 2022).
