### ISSUE TITLE
Windows 11 22H2 2013-11 CU not downloading

### ISSUE THREAD

**Issue by xe0n11** [OSDeploy/OSDSUS#8]
FYI - Noticed the 2023-11 CU for Windows 11 22H2 isn't downloading after the latest update.

Error in the catalog files?

**Comment by Simsi1986** [comment]
Yes, unfortunately CU for Windows 11 are missing. Hopefully fixed after the weekend with reference to other comments from OSDeploy. Root cause is, that handling of CUs for Win11 has changed earlier this year, which requires add. manuall effort to maintain the catalog. (no cabs published, msu are used)

**Comment by xe0n11** [comment]
Yup, I'm aware.

**Comment by xe0n11** [comment]
Are you able to upload the latest OSDSUS release (23.12.18.1) to PowerShell Gallery? Thanks!

Happy Christmas 🎄🍻

**Comment by OSDeploy** [comment]
Sorry, family in town but I should have this updated tonight.
